blacklist = ["^scratch$", "^_"]

[[wildcard]]
pattern = "~/repos/*"
startup_command = "nvim"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "screenshots"
path = "~/Pictures/Screenshots"
startup_command = "yazi"

[[session]]
name = "music"
startup_command = "lazyspotify"

[[session]]
name = "dots"
path = "~/dots-fedora"
startup_command = "nvim"
